---
apiVersion: v1
kind: Template
metadata:
  name: fluentd-forwarder-bc
  annotations:
    description: Build Config template for collecting and forwarding fluentd logs to a remote log collection point like rsyslog or splunk.
labels:
  name: fluentd-forwarder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: rhel7
    labels:
      app: fluentd-forwarder
  spec:
    tags:
      - name: latest
        annotations:
          openshift.io/imported-from: registry.access.redhat.com/rhel7/rhel
        from:
          kind: DockerImage
          name: registry.access.redhat.com/rhel7/rhel
        referencePolicy:
          type: Source
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${IMAGE_NAME}
    labels:
      app: fluentd-forwarder
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${IMAGE_NAME}
    labels:
      app: ${IMAGE_NAME}
  spec:
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: ${GIT_URI}
        ref: ${GIT_REF}
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: 'rhel7:latest'
    output:
      to:
        kind: ImageStreamTag
        name: '${IMAGE_NAME}:latest'
parameters:
  - name: GIT_URI
    description: The Git URI.
    value: "https://github.com/CDCgov/openshift-fluentd-forwarder.git"
    required: true
  - name: GIT_REF
    description: The git reference (tag, branch or other reference) to build from.
    value: master
    required: true
  - name: IMAGE_NAME
    description: The name of the image to be used when performing the pull operation.
    value: fluentd-forwarder
    required: true
